site_name: OriginBot智能机器人开源套件
site_url: https://www.guyuehome.com
repo_name: originbot
repo_url: https://gitee.com/guyuehome/originbot
site_description: 'OriginBot智能机器人开源套件·古月居'
copyright: © 2021 古月居 鄂ICP备18024451号-2

nav:
    - 项目主页: index.md
    - 使用指引: guide/quick_guide.md
    - 套件资料: 
        - 套件清单: material/material_list.md
        - 资料链接: material/open_source_link.md
        - 接口说明: material/hardware_interface.md
        - 常用软件: material/common_software.md
    - 硬件组装: guide/hardware_setup.md
    - 软件配置:
        - 镜像安装与备份: guide/image_install.md
        - 控制器固件安装: guide/firmware_install.md
        - 电脑端环境配置: guide/pc_config.md
    - 快速上手: guide/easy_start.md
    - 基础使用:
        - 搭建开发环境: manual/ide_setup.md
        - 代码开发方法: manual/package_develop.md
        - 机器人启动与参数配置: manual/originbot_bringup.md
        - 机器人遥控与可视化: manual/teleoperation.md
        - 相机驱动与可视化: manual/camera_visualization.md
        - 雷达驱动与可视化: manual/lidar_visualization.md
        - IMU驱动与可视化: manual/imu_visualization.md
        - 机器人参数动态监控: manual/parameter_config.md
        - 机器人里程计校准: manual/odom_calibration.md
        - 机器人充电方法: manual/originbot_charging.md
        - 通信协议说明: manual/protocol_description.md
        - 上位机控制说明: manual/hmi.md
        - 实时操作系统RTOS配置: manual/originbot_freertos.md
        - EKF多传感器融合定位: manual/ekf.md
        - WebViz可视化: manual/webviz.md
    - 应用功能:
        - 基础功能编程: application/basic_program.md
        - Gazebo虚拟仿真: application/gazebo_simulation.md
        - SLAM地图构建(Gazebo): application/gazebo_slam.md
        - SLAM地图构建: application/slam.md
        - 自主导航(Gazebo): application/gazebo_navigation.md
        - 自主导航: application/navigation.md
        - 人体跟踪: application/body_detection.md        
        - 手势控制: application/gesture_control.md
        - 视觉巡线(OpenCV): application/cv_line_follower.md
        - 视觉巡线(AI深度学习): application/deeplearning_line_follower.md
        - 视觉巡线(Gazebo): application/gazebo_line_follower.md
        - 车位寻找(AI深度学习): application/parking_search.md
        - 踢球射门: application/play_football.md
        - 轨迹跟踪 : application/tracking.md
        # - 语音控制 : application/audio_control.md
        - 图像获取 : application/take_pictures.md
        - 二维码识别与跟踪 : application/qrcode_detection.md
        - 车牌识别 : application/vlpr.md
        - 分割一切 : application/mobilesam.md
    - 常见问题: reference/faq.md
    - 教学课程: course/courses.md
    - 参考资料: reference/reference.md
    - 更多套件: reference/third_party_kits.md
    - 更多内容:
        - 参与贡献: reference/contributing.md
        - 更新日志: reference/changelog.md
    - 社区交流: https://www.guyuehome.com/interlocution?id=1826932316801544194
    - 关于我们: about.md

    - Project Home: en/index.md
    - User Guide: en/guide/quick_guide.md
    - Kit Information: 
        - Kit List: en/material/material_list.md
        - Resources Link: en/material/open_source_link.md
        # - Interface Description: en/material/hardware_interface.md
        - Common Software: en/material/common_software.md
    - Hardware Assembly: en/guide/hardware_setup.md
    - Software Configuration:
        - Image Installation and Backup: en/guide/image_install.md
        - Controller Firmware Installation: en/guide/firmware_install.md
        - PC Environment Configuration: en/guide/pc_config.md
    - Quick Start: en/guide/easy_start.md
    - Basic Usage:
        - Robot Charging Method: en/manual/originbot_charging.md
        - Setting Up Development Environment: en/manual/ide_setup.md
        - Code Development Method: en/manual/package_develop.md
        - Robot Startup and Parameter Configuration: en/manual/originbot_bringup.md
        - Robot Teleoperation and Visualization: en/manual/teleoperation.md
        - Camera Driver and Visualization: en/manual/camera_visualization.md
        - Lidar Driver and Visualization: en/manual/lidar_visualization.md
        - IMU Driver and Visualization: en/manual/imu_visualization.md
        - Dynamic Monitoring of Robot Parameters: en/manual/parameter_config.md
        - Robot Odometer Calibration: en/manual/odom_calibration.md
        - Communication Protocol Description: en/manual/protocol_description.md
        - HMI Control Description: en/manual/hmi.md
        - Real-Time Operating System RTOS Configuration: en/manual/originbot_freertos.md
        - EKF Multi-Sensor Fusion Positioning: en/manual/ekf.md
        - WebViz Visualization: en/manual/webviz.md
    - Application Features:
        - Basic Function Programming: en/application/basic_program.md
        - Gazebo Virtual Simulation: en/application/gazebo_simulation.md
        - SLAM Map Building (Gazebo): en/application/gazebo_slam.md
        - SLAM Map Building: en/application/slam.md
        - Autonomous Navigation (Gazebo): en/application/gazebo_navigation.md
        - Autonomous Navigation: en/application/navigation.md
        - Human Body Tracking: en/application/body_detection.md        
        - Gesture Control: en/application/gesture_control.md
        - Visual Line Following (OpenCV): en/application/cv_line_follower.md
        - Visual Line Following (AI Deep Learning): en/application/deeplearning_line_follower.md
        - Visual Line Following (Gazebo): en/application/gazebo_line_follower.md
        - Parking Spot Finding (AI Deep Learning): en/application/parking_search.md
        - Playing Football: en/application/play_football.md
        - Trajectory Tracking: en/application/tracking.md
        # - Voice Control: en/application/audio_control.md
        - Image Acquisition: en/application/take_pictures.md
        - QR Code Detection and Tracking: en/application/qrcode_detection.md
        - License Plate Recognition: en/application/vlpr.md
        - Segment Everything : en/application/mobilesam.md
    # - FAQ: en/reference/faq.md
    # - Teaching Courses: en/course/courses.md
    # - Reference Materials: en/reference/reference.md
    # - More Kits: en/reference/third_party_kits.md
    - More Content:
        - Contributing: en/reference/contributing.md
        - Changelog: en/reference/changelog.md
    - Community Exchange: https://www.guyuehome.com/interlocution?id=1826932316801544194
    - About Us: en/about.md

    
theme: 
    name: material
    logo: assets/img/favicon.png
    favicon: assets/img/favicon.png
    font: Incosolata    
    features:
        #- navigation.expand
        - search.highlight
        #- header.autohide
        - content.code.copy
    palette:
        - scheme: default
          primary: green
          accent: green
          toggle:
            icon: material/toggle-switch  
            name: Switch to dark mode
        - scheme: slate
          primary: green
          accent: green
          toggle:
            icon: material/toggle-switch-off-outline
            name: Switch to light mode
    font:
        text: Roboto
        code: Roboto Mono

plugins:
  - search:
      lang:
        - en
        - ja
      separator: '[\s\-\.]+'
  - i18n:
      default_language: zh
      languages:
        - locale: zh
          name: 中文
          default: true
          build: true
        - locale: en
          name: English
          build: true
            
markdown_extensions:
    - markdown.extensions.attr_list
    - pymdownx.superfences
    - pymdownx.tabbed
    - pymdownx.tabbed:
        alternate_style: true
    - pymdownx.keys
    - pymdownx.snippets
    - pymdownx.inlinehilite
    - pymdownx.highlight:
        use_pygments: true
        anchor_linenums: true
    - admonition
    - pymdownx.details
    - pymdownx.superfences
    - pymdownx.highlight
    - attr_list
    - pymdownx.emoji:
         emoji_index: !!python/name:material.extensions.emoji.twemoji
         emoji_generator: !!python/name:material.extensions.emoji.to_svg
    - codehilite

extra_css:
    - 'assets/css/extensions.css'
    - 'assets/css/simpleLightbox.min.css'
    - 'assets/css/custom.css'
  
extra_javascript:  
    - 'assets/js/baidu-tongji.js'
    - 'https://code.jquery.com/jquery-3.2.1.min.js'
    - 'assets/js/simpleLightbox.min.js'
    - 'assets/js/extensions.js'
    - 'assets/js/custom.js'
  
extra:
    social:
        - icon: fontawesome/solid/blog
          link: https://www.guyuehome.com
        - icon: fontawesome/solid/book-open
          link: https://class.guyuehome.com
        - icon: fontawesome/brands/bilibili
          link: https://space.bilibili.com/386919562
        - icon: fontawesome/brands/git-alt
          link: https://gitee.com/guyuehome          
        - icon: fontawesome/brands/github
          link: https://github.com/guyuehome
        - icon: fontawesome/solid/code
          link: https://developer.d-robotics.cc/          

extra:
  alternate:
    - name: English
      link: /botwebtest/en/
      lang: en
    - name: 简体中文
      link: /botwebtest/
      lang: zh